// Comprehensive list of Indian colleges — national to state/town level.
// The exported COLLEGE_LIST is de-duplicated and sorted alphabetically.
const _RAW_COLLEGE_LIST = [

  // ── IITs ──────────────────────────────────────────────────────────────────
  'Indian Institute of Technology (ISM) Dhanbad',
  'Indian Institute of Technology Bhilai',
  'Indian Institute of Technology Bhubaneswar',
  'Indian Institute of Technology Bombay',
  'Indian Institute of Technology Delhi',
  'Indian Institute of Technology Dharwad',
  'Indian Institute of Technology Gandhinagar',
  'Indian Institute of Technology Goa',
  'Indian Institute of Technology Guwahati',
  'Indian Institute of Technology Hyderabad',
  'Indian Institute of Technology Indore',
  'Indian Institute of Technology Jammu',
  'Indian Institute of Technology Jodhpur',
  'Indian Institute of Technology Kanpur',
  'Indian Institute of Technology Kharagpur',
  'Indian Institute of Technology Madras',
  'Indian Institute of Technology Mandi',
  'Indian Institute of Technology Palakkad',
  'Indian Institute of Technology Patna',
  'Indian Institute of Technology Roorkee',
  'Indian Institute of Technology Ropar',
  'Indian Institute of Technology Tirupati',
  'Indian Institute of Technology BHU Varanasi',

  // ── IIITs ─────────────────────────────────────────────────────────────────
  'Indian Institute of Information Technology & Management Gwalior',
  'Indian Institute of Information Technology Agartala',
  'Indian Institute of Information Technology Allahabad',
  'Indian Institute of Information Technology Bhagalpur',
  'Indian Institute of Information Technology Bhopal',
  'Indian Institute of Information Technology Dharwad',
  'Indian Institute of Information Technology Design & Manufacturing Jabalpur',
  'Indian Institute of Information Technology Design & Manufacturing Kancheepuram',
  'Indian Institute of Information Technology Guwahati',
  'Indian Institute of Information Technology Kalyani',
  'Indian Institute of Information Technology Kottayam',
  'Indian Institute of Information Technology Lucknow',
  'Indian Institute of Information Technology Manipur',
  'Indian Institute of Information Technology Nagpur',
  'Indian Institute of Information Technology Pune',
  'Indian Institute of Information Technology Ranchi',
  'Indian Institute of Information Technology Srirangam',
  'Indian Institute of Information Technology Surat',
  'Indian Institute of Information Technology Vadodara',
  'International Institute of Information Technology Bangalore',
  'International Institute of Information Technology Hyderabad',
  'International Institute of Information Technology Naya Raipur',

  // ── NITs ──────────────────────────────────────────────────────────────────
  'Dr B R Ambedkar National Institute of Technology Jalandhar',
  'Malaviya National Institute of Technology Jaipur',
  'Maulana Azad National Institute of Technology Bhopal',
  'Motilal Nehru National Institute of Technology Allahabad',
  'National Institute of Technology Agartala',
  'National Institute of Technology Andhra Pradesh',
  'National Institute of Technology Arunachal Pradesh',
  'National Institute of Technology Calicut',
  'National Institute of Technology Delhi',
  'National Institute of Technology Durgapur',
  'National Institute of Technology Goa',
  'National Institute of Technology Hamirpur',
  'National Institute of Technology Jamshedpur',
  'National Institute of Technology Karnataka Surathkal',
  'National Institute of Technology Kurukshetra',
  'National Institute of Technology Manipur',
  'National Institute of Technology Meghalaya',
  'National Institute of Technology Mizoram',
  'National Institute of Technology Nagaland',
  'National Institute of Technology Patna',
  'National Institute of Technology Puducherry',
  'National Institute of Technology Raipur',
  'National Institute of Technology Rourkela',
  'National Institute of Technology Sikkim',
  'National Institute of Technology Silchar',
  'National Institute of Technology Srinagar',
  'National Institute of Technology Tiruchirappalli',
  'National Institute of Technology Uttarakhand',
  'National Institute of Technology Warangal',
  'Sardar Vallabhbhai National Institute of Technology Surat',
  'Visvesvaraya National Institute of Technology Nagpur',

  // ── IISc / IISERs ─────────────────────────────────────────────────────────
  'Indian Institute of Science Bangalore',
  'Indian Institute of Science Education and Research Bhopal',
  'Indian Institute of Science Education and Research Kolkata',
  'Indian Institute of Science Education and Research Mohali',
  'Indian Institute of Science Education and Research Pune',
  'Indian Institute of Science Education and Research Thiruvananthapuram',
  'Indian Institute of Science Education and Research Tirupati',

  // ── BITS Pilani ───────────────────────────────────────────────────────────
  'Birla Institute of Technology and Science, Pilani',
  'Birla Institute of Technology and Science, Pilani (Goa Campus)',
  'Birla Institute of Technology and Science, Pilani (Hyderabad Campus)',

  // ── Central Universities ──────────────────────────────────────────────────
  'Aligarh Muslim University',
  'Banaras Hindu University',
  'Central University of Rajasthan',
  'Hyderabad Central University',
  'Pondicherry University',
  'Tezpur University',
  'University of Delhi',
  'University of Hyderabad',

  // ── Andhra Pradesh ────────────────────────────────────────────────────────
  'Aditya College of Engineering Surampalem',
  'Andhra University College of Engineering Visakhapatnam',
  'Aurora\'s Engineering College Bhongir',
  'Bapatla Engineering College',
  'Dhanekula Institute of Engineering and Technology Vijayawada',
  'GVP College of Engineering Visakhapatnam',
  'Gayatri Vidya Parishad College of Engineering Visakhapatnam',
  'JNTUK University College of Engineering Kakinada',
  'KL University Vijayawada',
  'Lakireddy Bali Reddy College of Engineering Mylavaram',
  'MVGR College of Engineering Vizianagaram',
  'Pragati Engineering College Surampalem',
  'R.V.R. & J.C. College of Engineering Guntur',
  'Raghu Engineering College Visakhapatnam',
  'Sri Vasavi Engineering College Tadepalligudem',
  'Srinivasa Institute of Engineering and Technology Amalapuram',
  'Swarnandhra College of Engineering and Technology Narsapur',
  'Vignan\'s Foundation for Science Technology & Research Guntur',
  'Vignan\'s Institute of Information Technology Visakhapatnam',

  // ── Assam & North-East ────────────────────────────────────────────────────
  'Assam Engineering College Guwahati',
  'Assam Science and Technology University',
  'Central Institute of Technology Kokrajhar',
  'Girijananda Chowdhury Institute of Management and Technology Guwahati',
  'Jorhat Engineering College',
  'Royal Global University Guwahati',
  'Sikkim Manipal Institute of Technology Rangpo',

  // ── Bihar & Jharkhand ─────────────────────────────────────────────────────
  'Aryabhatta Knowledge University Patna',
  'BIT Mesra Ranchi',
  'BIT Sindri Dhanbad',
  'Bihar College of Engineering Patna',
  'CIT Tatisilwai',
  'Cambridge Institute of Technology Ranchi',
  'Government Engineering College Bhagalpur',
  'Government Engineering College Nawada',
  'Haldia Institute of Technology',
  'Muzaffarpur Institute of Technology',

  // ── Chandigarh / Punjab ───────────────────────────────────────────────────
  'Chandigarh College of Engineering and Technology',
  'Chandigarh University',
  'Chitkara University Punjab',
  'Computer Science and Engineering, NIT Kurukshetra',
  'DAV Institute of Engineering and Technology Jalandhar',
  'Doaba College of Engineering and Technology',
  'Guru Nanak Dev Engineering College Ludhiana',
  'Guru Nanak Dev University Amritsar',
  'Lala Lajpat Rai Institute of Engineering and Technology Moga',
  'Lovely Professional University Phagwara',
  'Punjab Engineering College Chandigarh',
  'Punjabi University Patiala',
  'Sri Guru Granth Sahib World University Fatehgarh Sahib',
  'Thapar Institute of Engineering and Technology Patiala',
  'University Institute of Engineering and Technology, Panjab University',

  // ── Chhattisgarh ─────────────────────────────────────────────────────────
  'Bhilai Institute of Technology Durg',
  'Chhattisgarh Swami Vivekananda Technical University',
  'Government Engineering College Bilaspur',
  'Government Engineering College Jagdalpur',
  'Rungta College of Engineering and Technology Bhilai',
  'Shri Shankaracharya Institute of Professional Management and Technology Raipur',

  // ── Delhi / NCR ───────────────────────────────────────────────────────────
  'Ambedkar Institute of Advanced Communication Technologies and Research',
  'Amity University Noida',
  'Delhi Technological University',
  'Galgotias University Greater Noida',
  'GL Bajaj Institute of Technology and Management Greater Noida',
  'Guru Gobind Singh Indraprastha University',
  'Indira Gandhi Delhi Technical University for Women',
  'Indraprastha Institute of Information Technology Delhi',
  'Jamia Millia Islamia',
  'Jawaharlal Nehru University',
  'KIET Group of Institutions Ghaziabad',
  'Maharaja Agrasen Institute of Technology Delhi',
  'Netaji Subhas University of Technology',
  'Sharda University Greater Noida',
  'Shiv Nadar University Greater Noida',

  // ── Goa ───────────────────────────────────────────────────────────────────
  'Don Bosco College of Engineering Fatorda',
  'Goa College of Engineering Farmagudi',
  'Padre Conceicao College of Engineering Verna',
  'Shree Damodar College of Commerce and Economics Margao',

  // ── Gujarat ───────────────────────────────────────────────────────────────
  'Adani Institute of Infrastructure Engineering Ahmedabad',
  'Ahmedabad Institute of Technology',
  'BVM Engineering College Anand',
  'C. U. Shah University Wadhwan',
  'Chandubhai S Patel Institute of Technology Anand',
  'Dhirubhai Ambani Institute of Information and Communication Technology Gandhinagar',
  'GH Patel College of Engineering and Technology Anand',
  'Ganpat University Mehsana',
  'Government Engineering College Bharuch',
  'Government Engineering College Gandhinagar',
  'Government Engineering College Rajkot',
  'Government Engineering College Surat',
  'LD College of Engineering Ahmedabad',
  'Lalbhai Dalpatbhai College of Engineering Ahmedabad',
  'Marwadi University Rajkot',
  'Nirma University Ahmedabad',
  'Pandit Deendayal Energy University Gandhinagar',
  'Sarvajanik College of Engineering and Technology Surat',
  'Sankalchand Patel University Visnagar',
  'Shantilal Shah Engineering College Bhavnagar',
  'Silver Oak University Ahmedabad',
  'Tatva Institute of Technological Studies Modasa',

  // ── Haryana ───────────────────────────────────────────────────────────────
  'Deenbandhu Chhotu Ram University of Science and Technology Murthal',
  'GJU Science and Technology Hisar',
  'J.C. Bose University of Science and Technology YMCA Faridabad',
  'Maharishi Markandeshwar University Mullana',
  'PDM University Bahadurgarh',

  // ── Himachal Pradesh ──────────────────────────────────────────────────────
  'Jaypee University of Information Technology Waknaghat',
  'Shoolini University Solan',

  // ── Jammu & Kashmir ───────────────────────────────────────────────────────
  'Government College of Engineering and Technology Jammu',
  'Islamic University of Science and Technology Awantipora',
  'Model Institute of Engineering and Technology Jammu',
  'University of Jammu',
  'University of Kashmir Srinagar',

  // ── Karnataka ─────────────────────────────────────────────────────────────
  'B.M.S. College of Engineering Bangalore',
  'Bangalore Institute of Technology',
  'Christ University Bangalore',
  'CMR College of Engineering and Technology Bangalore',
  'CMR Institute of Technology Bangalore',
  'Dayananda Sagar College of Engineering Bangalore',
  'Dr. Ambedkar Institute of Technology Bangalore',
  'East West College of Engineering Bangalore',
  'GITAM School of Technology Bangalore',
  'JSS Science and Technology University Mysore',
  'KLE Technological University Hubballi',
  'KVG College of Engineering Sullia',
  'Malnad College of Engineering Hassan',
  'Manipal Institute of Technology Manipal',
  'MS Ramaiah Institute of Technology Bangalore',
  'MVJ College of Engineering Bangalore',
  'Nitte Meenakshi Institute of Technology Bangalore',
  'P.A. College of Engineering Mangalore',
  'PES University Bangalore',
  'PESIT South Campus Bangalore',
  'RNS Institute of Technology Bangalore',
  'RV College of Engineering Bangalore',
  'Sahyadri College of Engineering and Management Mangalore',
  'SDM College of Engineering and Technology Dharwad',
  'Siddaganga Institute of Technology Tumkur',
  'Sir M. Visvesvaraya Institute of Technology Bangalore',
  'St. Joseph Engineering College Mangalore',
  'The National Institute of Engineering Mysore',
  'Visvesvaraya Technological University Belagavi',

  // ── Kerala ────────────────────────────────────────────────────────────────
  'APJ Abdul Kalam Technological University',
  'College of Engineering Chengannur',
  'College of Engineering Kidangoor',
  'College of Engineering Kottayam',
  'College of Engineering Munnar',
  'College of Engineering Perumon',
  'College of Engineering Trivandrum',
  'Cochin University of Science and Technology',
  'Federal Institute of Science and Technology Angamaly',
  'Government Engineering College Barton Hill Trivandrum',
  'Government Engineering College Idukki',
  'Government Engineering College Kozhikode',
  'Government Engineering College Palakkad',
  'Government Engineering College Thrissur',
  'Government Engineering College Wayanad',
  'Ilahia College of Engineering and Technology Muvattupuzha',
  'LBS College of Engineering Kasaragod',
  'Mar Athanasius College of Engineering Kothamangalam',
  'Model Engineering College Thrikkakara',
  'Mount Zion College of Engineering Pathanamthitta',
  'Rajiv Gandhi Institute of Technology Kottayam',
  'Sree Buddha College of Engineering Pattoor',
  'Sree Krishna College of Engineering and Technology Payyoli',
  'TKM College of Engineering Kollam',
  'Toc H Institute of Science and Technology Ernakulam',
  'Vidya Academy of Science and Technology Thrissur',

  // ── Madhya Pradesh ────────────────────────────────────────────────────────
  'LNCT Group Bhopal',
  'Medi-Caps University Indore',
  'Oriental Institute of Science and Technology Bhopal',
  'SAGE University Indore',
  'SGSITS Indore',
  'Shri Govindram Seksaria Institute of Technology and Science Indore',
  'Technocrats Institute of Technology Bhopal',
  'Truba Institute of Engineering Bhopal',

  // ── Maharashtra ───────────────────────────────────────────────────────────
  'Amrutvahini College of Engineering Sangamner',
  'Atharva College of Engineering Mumbai',
  'Bharati Vidyapeeth College of Engineering Pune',
  'Cummins College of Engineering for Women Pune',
  'D.Y. Patil College of Engineering Akurdi Pune',
  'Fr. Conceicao Rodrigues College of Engineering Bandstand Mumbai',
  'G.H. Raisoni College of Engineering Nagpur',
  'Government College of Engineering Amravati',
  'Government College of Engineering Aurangabad',
  'Government College of Engineering Chandrapur',
  'Government College of Engineering Jalgaon',
  'Government College of Engineering Karad',
  'Government College of Engineering Nagpur',
  'Government College of Engineering Osmanabad',
  'Government College of Engineering Pune',
  'Institute of Chemical Technology Mumbai',
  'K. J. Somaiya College of Engineering Mumbai',
  'Maharashtra Institute of Technology Pune',
  'Maharashtra Institute of Technology Aurangabad',
  'Marathwada Institute of Technology Aurangabad',
  'MGMCET Nanded',
  'MH Saboo Siddik College of Engineering Mumbai',
  'MIT Academy of Engineering Alandi',
  'Modern Education Society\'s College of Engineering Pune',
  'Pillai College of Engineering New Panvel',
  'Pune Institute of Computer Technology',
  'Ramrao Adik Institute of Technology Nerul',
  'Sardar Patel College of Engineering Mumbai',
  'Shah and Anchor Kutchhi Engineering College Mumbai',
  'Shri Ramdeobaba College of Engineering and Management Nagpur',
  'Sinhgad College of Engineering Vadgaon Pune',
  'Sinhgad Institute of Technology and Science Narhe Pune',
  'Symbiosis Institute of Technology Pune',
  'Trinity College of Engineering and Research Pune',
  'Veermata Jijabai Technological Institute Mumbai',
  'Vishwakarma Institute of Information Technology Pune',
  'Vishwakarma Institute of Technology Pune',
  'Walchand College of Engineering Sangli',
  'Yeshwantrao Chavan College of Engineering Nagpur',
  'Zeal College of Engineering and Research Pune',

  // ── Odisha ────────────────────────────────────────────────────────────────
  'C.V. Raman Global University Bhubaneswar',
  'CET Bhubaneswar',
  'Gandhi Institute for Technological Advancement Bhubaneswar',
  'Gandhi Institute of Technology and Management Visakhapatnam',
  'ITER, Siksha \'O\' Anusandhan University',
  'KIIT University Bhubaneswar',
  'Parala Maharaja Engineering College Berhampur',
  'Silicon Institute of Technology Bhubaneswar',
  'Veer Surendra Sai University of Technology Sambalpur',

  // ── Rajasthan ─────────────────────────────────────────────────────────────
  'Arya College of Engineering and IT Jaipur',
  'Government Engineering College Ajmer',
  'Government Engineering College Bikaner',
  'Government Engineering College Jhalawar',
  'Government Engineering College Kota',
  'Government Engineering College Tonk',
  'IIS University Jaipur',
  'LNM Institute of Information Technology Jaipur',
  'Manipal University Jaipur',
  'Poornima College of Engineering Jaipur',
  'Poornima Institute of Engineering and Technology Jaipur',
  'JECRC University Jaipur',

  // ── Tamil Nadu ────────────────────────────────────────────────────────────
  'Alagappa Chettiar Government College of Engineering and Technology Karaikudi',
  'Amrita College of Engineering and Technology Ettimadai',
  'Bannari Amman Institute of Technology Sathyamangalam',
  'BS Abdur Rahman Crescent Institute of Science and Technology Chennai',
  'Coimbatore Institute of Technology',
  'College of Engineering Guindy, Anna University',
  'DMI College of Engineering Chennai',
  'Easwari Engineering College Chennai',
  'Er. Perumal Manimekalai College of Engineering Hosur',
  'Government College of Engineering Bargur',
  'Government College of Engineering Dharmapuri',
  'Government College of Engineering Erode',
  'Government College of Engineering Krishnagiri',
  'Government College of Engineering Salem',
  'Government College of Engineering Tirunelveli',
  'Government College of Technology Coimbatore',
  'Hindusthan College of Engineering and Technology Coimbatore',
  'Info Institute of Engineering Coimbatore',
  'Karpagam College of Engineering Coimbatore',
  'KCG College of Technology Chennai',
  'Kongu Engineering College Erode',
  'Kumaraguru College of Technology Coimbatore',
  'Mepco Schlenk Engineering College Sivakasi',
  'PSG College of Technology Coimbatore',
  'Rajalakshmi Engineering College Chennai',
  'Rajalakshmi Institute of Technology Chennai',
  'SNS College of Engineering Coimbatore',
  'SNS College of Technology Coimbatore',
  'Sri Krishna College of Engineering and Technology Coimbatore',
  'Sri Krishna College of Technology Coimbatore',
  'Sri Ramakrishna Engineering College Coimbatore',
  'Sri Sai Ram Engineering College Chennai',
  'Sri Venkateswara College of Engineering Sriperumbudur',
  'SSN College of Engineering Kalavakkam',
  'St. Joseph\'s College of Engineering Chennai',
  'SRM Institute of Science and Technology Kattankulathur',
  'SRM Valliammai Engineering College Kattankulathur',
  'Thiagarajar College of Engineering Madurai',
  'Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology',
  'Velammal Engineering College Chennai',
  'Velammal Institute of Technology Panchetti',

  // ── Telangana ─────────────────────────────────────────────────────────────
  'Chaitanya Bharathi Institute of Technology Hyderabad',
  'CVR College of Engineering Hyderabad',
  'G Narayanamma Institute of Technology and Science Hyderabad',
  'Geethanjali College of Engineering and Technology Hyderabad',
  'Gokaraju Rangaraju Institute of Engineering and Technology Hyderabad',
  'JNTUH College of Engineering Hyderabad',
  'JNTUH College of Engineering Jagtial',
  'JNTUH College of Engineering Sulthanpur',
  'Kakatiya Institute of Technology and Science Warangal',
  'Mahatma Gandhi Institute of Technology Hyderabad',
  'MVSR Engineering College Nadergul',
  'Osmania University College of Engineering Hyderabad',
  'Sreenidhi Institute of Science and Technology Hyderabad',
  'SR Engineering College Warangal',
  'Vardhaman College of Engineering Hyderabad',
  'Vasavi College of Engineering Hyderabad',

  // ── Uttar Pradesh ─────────────────────────────────────────────────────────
  'Ajay Kumar Garg Engineering College Ghaziabad',
  'Babu Banarasi Das University Lucknow',
  'Dr. A.P.J. Abdul Kalam Technical University Lucknow',
  'GLA University Mathura',
  'Harcourt Butler Technical University Kanpur',
  'Institute of Engineering and Technology Lucknow',
  'Jaypee Institute of Information Technology Noida',
  'JSS Academy of Technical Education Noida',
  'Kamla Nehru Institute of Technology Sultanpur',
  'Meerut Institute of Engineering and Technology',
  'Raj Kumar Goel Institute of Technology Ghaziabad',
  'Shri Ramswaroop Memorial College of Engineering and Management Lucknow',

  // ── Uttarakhand ───────────────────────────────────────────────────────────
  'Graphic Era University Dehradun',
  'Jaypee University of Engineering and Technology',
  'University of Petroleum and Energy Studies Dehradun',

  // ── West Bengal ───────────────────────────────────────────────────────────
  'Calcutta Institute of Engineering and Management',
  'Dream Institute of Technology Kolkata',
  'Future Institute of Engineering and Management Sonarpur',
  'Government College of Engineering and Ceramic Technology Kolkata',
  'Government College of Engineering and Leather Technology Kolkata',
  'Heritage Institute of Technology Kolkata',
  'IIEST Shibpur',
  'Institute of Engineering and Management Kolkata',
  'Jadavpur University',
  'JIS College of Engineering Kalyani',
  'Kalyani Government Engineering College',
  'Maulana Abul Kalam Azad University of Technology West Bengal',
  'Narula Institute of Technology Kolkata',
  'RCC Institute of Information Technology Kolkata',
  'Siliguri Institute of Technology',
  'Swami Vivekananda Institute of Science and Technology Kolkata',
  'Techno India Group Kolkata',
  'University of Engineering and Management Kolkata',
  'University of Engineering and Management Jaipur',

  // ── Maharashtra (Private/Deemed) ──────────────────────────────────────────
  'Amity University Mumbai',
  'FLAME University Pune',
  'MIT World Peace University Pune',
  'Narsee Monjee Institute of Management Studies Mumbai',
  'Somaiya Vidyavihar University Mumbai',
  'Symbiosis International University Pune',

  // ── South (Other) ─────────────────────────────────────────────────────────
  'Amrita Vishwa Vidyapeetham Coimbatore',
  'Amrita Vishwa Vidyapeetham Bangalore',
  'Amrita Vishwa Vidyapeetham Kochi',
  'Manipal Academy of Higher Education',
  'Vellore Institute of Technology',
  'Vellore Institute of Technology Chennai',
  'Vellore Institute of Technology Bhopal',
  'Vellore Institute of Technology AP Amaravati',
];

// De-duplicate and sort alphabetically
const COLLEGE_LIST = [...new Set(_RAW_COLLEGE_LIST)].sort();

export default COLLEGE_LIST;
